# Generated by Django 3.1 on 2024-03-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20240321_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cart_image',
            new_name='cat_image',
        ),
    ]
